WIP: STOR-1263: Bump k8s 1.27
openshift/client-go pull request #237
Opened 2023-03-20 19:22 UTC by bertinatto

2023-03-21 12:05 UTC, soltysh requested changes

2023-03-21 12:05 UTC, soltysh commented on go.mod
>  	k8s.io/code-generator v0.26.1
Those need to be bumped to `v0.27.0-beta.0` as well, everything that has `k8s.io/...` and ends with `0.26` is eligible for bump. All the rest should match what k8s has.

2023-04-28 11:05 UTC, soltysh approved these changes
/lgtm
/approve
/hold to not accidentally merge this :sweat_smile:  due to fake api bump

2023-05-03 13:55 UTC, deads2k commented on go.mod
> +	k8s.io/kube-openapi => github.com/openshift/kube-openapi v0.0.0-20230324164143-98c122c21a89
This will not be pulled into repos depending on openshift/client-go, if consumers of client-go need this, it won't fix it.

2023-05-03 14:41 UTC, merged